# # -*- coding: utf-8 -*-

# # Form implementation generated from reading ui file 'settings.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.9
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.


# from PyQt5 import QtCore, QtGui, QtWidgets


# class Ui_settings(object):
#     def setupUi(self, settings):
#         settings.setObjectName("settings")
#         settings.resize(348, 298)
#         self.verticalLayout = QtWidgets.QVBoxLayout(settings)
#         self.verticalLayout.setObjectName("verticalLayout")
#         self.opacity = QtWidgets.QVBoxLayout()
#         self.opacity.setObjectName("opacity")
#         self.opacity_text = QtWidgets.QLabel(settings)
#         self.opacity_text.setObjectName("opacity_text")
#         self.opacity.addWidget(self.opacity_text)
#         self.opacity_container = QtWidgets.QHBoxLayout()
#         self.opacity_container.setContentsMargins(5, 5, 5, 5)
#         self.opacity_container.setObjectName("opacity_container")
#         self.opacity_value = QtWidgets.QLabel(settings)
#         self.opacity_value.setAlignment(QtCore.Qt.AlignCenter)
#         self.opacity_value.setObjectName("opacity_value")
#         self.opacity_container.addWidget(self.opacity_value)
#         self.opacity_slider = QtWidgets.QSlider(settings)
#         self.opacity_slider.setMinimum(1)
#         self.opacity_slider.setMaximum(100)
#         self.opacity_slider.setProperty("value", 95)
#         self.opacity_slider.setOrientation(QtCore.Qt.Horizontal)
#         self.opacity_slider.setObjectName("opacity_slider")
#         self.opacity_container.addWidget(self.opacity_slider)
#         self.opacity_container.setStretch(0, 1)
#         self.opacity_container.setStretch(1, 5)
#         self.opacity.addLayout(self.opacity_container)
#         self.verticalLayout.addLayout(self.opacity)
#         self.buttonBox = QtWidgets.QDialogButtonBox(settings)
#         self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
#         self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
#         self.buttonBox.setObjectName("buttonBox")
#         self.verticalLayout.addWidget(self.buttonBox)

#         self.retranslateUi(settings)
#         self.buttonBox.accepted.connect(settings.accept) # type: ignore
#         self.buttonBox.rejected.connect(settings.reject) # type: ignore
#         QtCore.QMetaObject.connectSlotsByName(settings)

#     def retranslateUi(self, settings):
#         _translate = QtCore.QCoreApplication.translate
#         settings.setWindowTitle(_translate("settings", "Settings"))
#         self.opacity_text.setText(_translate("settings", "Opacity"))
#         self.opacity_value.setText(_translate("settings", "100"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     settings = QtWidgets.QDialog()
#     ui = Ui_settings()
#     ui.setupUi(settings)
#     settings.show()
#     sys.exit(app.exec_())
